{
  "__PACKAGE_UIDS__", " ",
  "__LOCALS_IN_TRACEBACK__", " ",
  "__ARRAY_RESERVED_WORD__", " ",
  "__CFG_MAX_LOCAL_VARIABLES__", "		50",
  "__SUPPRESS_ARGUMENT_WARNINGS__", " ",
  "__CALLOUT_HANDLES__", " ",
  "__SAVE_EXTENSION__", " \".o\"",
  "__DEFAULT_PRAGMAS__", " PRAGMA_WARNINGS + PRAGMA_ERROR_CONTEXT",
  "__PACKAGE_EXTERNAL__", " ",
  "__CONFIG_FILE_DIR__", " \"/home/mud/bin\"",
  "__HEARTBEAT_INTERVAL__", " 2000000",
  "__NO_LIGHT__", " ",
  "__SYSMALLOC__", " ",
  "__RESTRICTED_ED__", " ",
  "__ARRAY_STATS__", " ",
  "__ARGUMENTS_IN_TRACEBACK__", " ",
  "__SMALL_STRING_SIZE__", "     100",
  "__HEART_BEAT_CHUNK__", "      32",
  "__PACKAGE_CONTRIB__", " ",
  "__OLD_ED__", " ",
  "__CACHE_STATS__", " ",
  "__LARGE_STRING_SIZE__", "     1000",
  "__APPLY_CACHE_BITS__", " 11",
  "__STRING_STATS__", " ",
  "__NO_ANSI__", " ",
  "__SANE_EXPLODE_STRING__", " ",
  "__CFG_MAX_CALL_DEPTH__", "		50",
  "__LOG_CATCHES__", " ",
  "__MAX_SAVE_SVALUE_DEPTH__", " 25",
  "__MUDLIB_ERROR_HANDLER__", " ",
  "__CFG_EVALUATOR_STACK_SIZE__", " 	1000",
  "__CALLOUT_CYCLE_SIZE__", " 32",
  "__PACKAGE_SOCKETS__", " ",
  "__CFG_LIVING_HASH_SIZE__", "		4096",
  "__THIS_PLAYER_IN_CALL_OUT__", " ",
  "__REF_RESERVED_WORD__", " ",
  "__MESSAGE_BUFFER_SIZE__", " 4096",
  "__STRIP_BEFORE_PROCESS_INPUT__", " ",
  "__NEXT_MALLOC_DEBUG__", " ",
  "__PROFILE_FUNCTIONS__", " ",
  "__TRAP_CRASHES__", " ",
  "__LARGEST_PRINTABLE_STRING__", " 16384",
  "__PACKAGE_DEVELOP__", " ",
  "__COMMAND_BUF_SIZE__", "      2000",
  "__CFG_COMPILER_STACK_SIZE__", "		200",
  "__PACKAGE_MATH__", " ",
  "__SENSIBLE_MODIFIERS__", " ",
  "__NO_WIZARDS__", " ",
};

#define NUM_OPTION_DEFS 48

